doc/pandoc.txt

Just a minor typo. `g:pandoc#bibliographies#extensions` should be `g:pandoc#biblio#extensions`.
Confirmed that it does not occur except on one line.

minor typo

---

autoload/pandoc/hypertext.vim
autoload/pandoc/keyboard/links.vim
doc/pandoc.txt

- edit/split opening links now both possible.
- <localleader>gb should work for files, too.
- autosave on following a link in the same window, i.e. for edit-opening links.
- automatic creation of files that do not exist if
g:pandoc#hypertext#create_if_no_alternates_exists == 1

some additional hypertext functionality.

---

plugin/pandoc.vim

One should execute `pandoc#chdir#Init()` for each `BufEnter` as the current working directory is local to the window as opposed to local to the buffer.

pandoc#chdir#Init() called on BufEnter

---

autoload/pandoc/formatting.vim

Replace '--no-wrap' with '--wrap=none' since pandoc has deprecated the old option.

'--no-wrap' is deprecated

---

autoload/pandoc/command.vim

replace BuffWrite with BuffWritePost to make autoexec work in neovim

---

autoload/pandoc/hypertext.vim

The call to expand before calling ``xdg-open`` makes it possible to have links like ``[file](~/something/in/your/home)``. Moreover, the ``shellescape()`` deals with complicated filenames.

expand filename before calling xdg-open

---

pythonx/vim_pandoc/bib/fallback.py

By default bibtool does not preserve key case.
The modified (lower case) key is inserted by omni-completion, but then is not present in the original .bib file.

Call bibtool with --preserve.key.case=on

---

autoload/markdown/headers.vim

If we require only one - or = to denote a header, then the following
gets detected as a header:
- this line is not a header, but appears to be one
- just a dot point
This should fix #150.

Require more than one - or = in setext headers

---

autoload/pandoc/keyboard/styles.vim

Fixed the lineending detection for pandoc-keyboard-toggle-* commands.
now if the selected text is at the end of the line the beginning space
will not be absorbed.
see Issue #180

Fixed pandoc-keyboard-toggle-*

---

autoload/pandoc/formatting.vim
doc/pandoc.txt

Not everyone likes `--reference-links` and setting `equalprg` is
loses the `--columns/--wrap=none` logic.
This way it is still a default, but can be turned off.

put --reference-links in extra_equalprg

---

ftplugin/pandoc.vim

- matchit now recognizes math delimiters in pandoc 
- lists are recognized

add matchit and list patterns

---

pythonx/vim_pandoc/command.py

The regex to capture long options with optional arguments (like `--katex[=URL]`) fails due to the square brackets. The attached patch fixes this for me.

Fix regex to capture optional long options

---

doc/pandoc.txt
plugin/pandoc.vim

I suspect for many this isn't a major problem, but I'm finding the warnings about modules being disabled by default on older versions of vim becoming distracting. This PR adds a new configuration variable and checks it before issuing the warning.
The default behaviour is not changed - users must explicitly disable the warning by setting the variable.

Allow suppression of module-disabled warnings

---

autoload/pandoc/formatting.vim

`j` and `k` are currently unmapped in `autoload/formatting.vim` This restores them if they were remapped.
I also applied some linting suggestions from `vint`.
See the commits for more detail

restore user mappings for `j` and `k`

---

pythonx/vim_pandoc/command.py

In Pandoc 1.18 the help syntax to find input and output formats was
changed. To that end there was made an exception that checked
specifically for a version that was 1.18 in order to find the formats in
this new version. Pandoc is now in version 1.19 and follows the same
pattern as 1.18 and it is expected to continue like that, so as an easy
fix the if condition has been changed to include future versions as
well.

Add support for Pandoc 1.19 and above.

---

autoload/pandoc/folding.vim

R markdown files with extensions *.Rmd and *.rmd get the filetype
'rmd' assigned by vim and neovim.
ftplugin/rmd.vim sources ftplugin/pandoc.vim if it is installed.
This commit makes the syntax folding module work in this situation.

Enable folding when filetype=rmd

---

pythonx/vim_pandoc/bib/fallback.py

On the Mac, reading from BIBTool produces `bytes`, so that the `re.sub()` in `get_bibtex_suggestions()`
fails.
(On Linux, I get no such error; this is python 3.5 or 3.6 on the Mac with vim 8.0.237 built from MacPorts, and python 3.5 with vim 8.249 on Linux.)

bib/fallback.py: bibliography data can be bytes

---

pythonx/vim_pandoc/command.py

This PR modifies the parsing of pandoc arguments to allow existing logic around the expansion of `~` in paths to apply to pandoc arguments like `-V revealjs-url=~/.revealjs`.
It does so by re-coding the option and argument to be (in the above example) `-V revealjs` and `~/.revealjs` respectively.

Fix handling of paths for "-V var=valueorpath"-like arguments

---

pythonx/vim_pandoc/command.py

Previously, using arguments such as `Pandoc html -s` would produce a command like `pandoc -o a.html -s "" a.md`, resulting in pandoc complaining about a missing `""` file. This commit fixes this behavior by not adding extra quotes if an argument is only a flag.
Related: #219

python/pandoc/command: fix empty quoted arguments

---

pythonx/vim_pandoc/command.py

The return value of `vim.eval(...)` was being compared against an int
rather than a string, so that `custom_open` would never be considered a
valid Funcref.

python/command: fix custom_open never being considered

---

autoload/pandoc/command.vim
compiler/pandoc.vim
doc/pandoc.txt
pythonx/vim_pandoc/command.py

Since I mostly want to use _Panzer_ to create my documents using central style definitions, I built in three settings that allow users to define what program should be executed instead of `pandoc`.
My pandoc setup in vimrc looks like this:
```viml
let g:pandoc#compiler#command = 'panzer'
let g:pandoc#compiler#arguments = '---quiet ---strict'
```
The third setting, `g:pandoc#command#path` is only necessary if `pandoc` is not found in the user's PATH. _RStudio_, e.g., includes pandoc in its application bundle.
I hope I didn't overlook any place where a call to `pandoc` is hardcoded.

Add support for Panzer and other preprocessors

---

doc/pandoc.txt

The duplicate tag causes `:helptags` to emit an error when creating the documentation.

Fix duplicate help tag in doc

---

pythonx/vim_pandoc/command.py

pandoc 2 uses `gfm` instead of `markdown_github`

add new name for github markdown

---

autoload/pandoc/formatting.vim

In issue #198, some code was added to formatting.vim that is supposed to
restore user mappings for j and k, if they existed beforehand. The
normal mode mapping was being restored correctly, but the visual mode
mapping was still getting dropped on the floor. It turns out the blocks
for the visual and normal mappings were exact copies of each other. This
commit makes the minor tweak necessary to actually restore the visual
mode mappings.

Fixed bug with `j` and `k` user map restoration

---

autoload/pandoc/formatting.vim

The UseHardWraps function in formatting.vim uses unmap, which is why the
additions in issue #198 (and the small bugfix in issue #233) were
necessary. However, the fix introduced in #198 only restores normal and
visual mode mappings. unmap nukes normal, visual, AND operation-pending
modes (see :help mapmode-nvo in Vim). This fix adds one more block per
`j` and `k` to restore mappings to operation-pending mode as well.

Another fix to `j` and `k` restore

---

python3/vim_pandoc/command.py

Make sure the pandoc output window will actually close when `q` is
pressed.

Map `q` to `:bwipeout<CR>` instead of `:bd<CR>`.

---

autoload/pandoc/folding.vim
doc/pandoc.txt

unless using the inbuilt tweaks to folding performance.

pandoc/folding: don't disable foldexpr when there are multiple splits

---

python3/vim_pandoc/command.py

I am using neovim. If I open the file `sub/foo.md` and run `Pandoc!` the resulting `sub/foo.html` will not be opened.
This happens because in `command.py`, `self._output_file_path` is set to `sub/foo.html` and the current directory is `sub/`. Then the absolute path will be `sub/sub/foo.html` which is incorrect. Changing the `os.chdir()` call to change to the current vim working directory instead of the directory of the current buffer fixes the problem.
I don't know why the working directory was changed in that way, so I might have broken something.

Fix Pandoc! for neovim and subdirectory

---

python3/vim_pandoc/helpparser.py

This PR fixes the bug mentionned in #320.
Indeed, after an in-depth study, when I call `pandoc --version` from my MinGW64 terminal I get:
```
pandoc.exe 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: C:\Users\xx\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
Whereas from a `cmd.exe`, I get:
```
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: C:\Users\xx\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the …
```

Fix vim-pandoc usage with MSYS

---

ftplugin/pandoc.vim

Could help with https://github.com/Konfekt/vim-sentence-chopper/issues/1

reset options after switching filetype (to, say, markdown)

---

autoload/pandoc/command.vim

I would like to have `:Pandoc -o %:r.html` work if I don't have python installed.
#258

allow expansion of placeholders even if python not installed

---

autoload/pandoc/command.vim

vint was overzealous before, it tried to lint python as viml
@alerque Do you know why vint caught these before? I couldn't reproduce locally.

pandoc/command: fix comparisons in python calls

---

python3/vim_pandoc/bib/fallback.py

This seems to be required for python3.
I had a "unicode is not defined" error when trying omnicompletion with a CSL JSON bibliography file.

Use type 'str' instead of type 'unicode' for python3

---

autoload/pandoc/toc.vim

I think it is safe in this instance. The option is to search for matches in the file, and set the lines with a replacement; it strikes me as reinventing the wheel.
Re: #336

toc: bypass linter in safe case

---

autoload/pandoc/toc.vim
doc/pandoc.txt

Add new option to tune the indentation in TOC buffer: set the number of spaces per level. The default is 2. And make the statusline title of the toc buffer more readable.

Table of content improvements

---

doc/pandoc.txt

Hi,
I found a typo in the doc, I thought I would fix it for you.
Just one additional thought about this : what happens if `use_message_buffers` is set to `1` ? Maybe this documentation should say something like "for nvim parameter `use_message_buffers` is not considered".
Just a small contribution, please forgive me if this was not the right way to bring this up.
Matthias

Typo describing command behavior in nvim

---

autoload/pandoc/keyboard.vim
autoload/pandoc/keyboard/checkboxes.vim
doc/pandoc.txt

Checkboxes have been introduced by [Github Flavoured Markdown](https://github.github.com/gfm/#task-list-items-extension-) and are also supported in pandoc by the task_lists extension.

add keyboard submodule for checkboxes

---

ftdetect/pandoc.vim
plugin/pandoc.vim

Closes #349 
Need to review when `g:pandoc#filetypes#pandoc_markdown` might get set in relation to this.

Move ftdetect functions to proper location

---

ftdetect/pandoc.vim
plugin/pandoc.vim

Fixes this startup error for me:
```
Error detected while processing /home/doron/.files/.config/nvim/bundle/pandoc/plugin/pandoc.vim:
line   79:
E121: Undefined variable: g:pandoc#filetypes#pandoc_markdown
E15: Invalid expression: g:pandoc#filetypes#pandoc_markdown == 1
```
~~Might fix (NOT) https://github.com/vim-pandoc/vim-pandoc/issues/342 as well.~~

markdown filetype check: use get()

---

autoload/pandoc/command.vim

A better fix for issue #371 (compared to PR #372), in this one we only swap the order of the template and placeholder expansion.

Switch order of placeholder and template expansion so that templates can use placeholders

---

autoload/pandoc/folding.vim
doc/pandoc.txt

The foldlevel of the YAML frontmatter ist 1. The YAML frontmatter is rarely edited so the foldlevel should be customizable (i.e. higher). The default is 1 so this commit should not break any workflow.

Custom foldlevel for YAML frontmatters

---

autoload/pandoc/bibliographies.vim
doc/pandoc.txt
python3/vim_pandoc/bib/fallback.py

Otherwise bibtool errors with something like this:
```
@online{laurie_penny_who_2018,
_^
*** BibTool ERROR:  (line 1966 in ./zotero.bib): Unknown entry type
*** BibTool WARNING: Skipping to next '@'
```
This has the amusing property of making bibliographic completion appear elitist by excluding blog posts ;)
It's possible that using `-r biblatex` will break some features of non-biblatex .bibs, if that's a concern there are other workarounds here: https://github.com/ge-ne/bibtool/issues/2

Support `@online` in .bibs when using bibtool

---

autoload/pandoc/toc.vim

When calling TOC, all subsequent buffers seems to be non-modifiable. For example, when in an md file and opening TOC, closing it and opening a filename (using gf)
```{.lang=vimscript}
:TOC
:lclose
gf
```
The newly opened buffer is non modifiable. This PR solves this issue by setting the modifiable property locally to the created location list buffer

Change modifiable options to buffer local

---

doc/pandoc.txt

Docs mention a setting `folding_yaml` that doesn't exist in codebase. Fixing it.

Fix YAML foldlevel typo in docs

---

python3/vim_pandoc/helpparser.py

Re #327
The problem was that we only checked for the presence of `.exe` in case we detected `msys` as the platform. That is too strict. As @sticke4 pointed out, it seems like we can just allow for the presence of `.exe` as optional always. 
Additionally, we shouldn't have assumed that we would always want the first group from the output of `__raw_output(...)` in case we gave it a pattern. Instead, we should return the match object, and let the caller function do what it needs (like we now do in get_version(), where we now use a named group).

python/helpparser: fix version checking

---

autoload/pandoc/toc.vim

Closes #368
Makes `:let g:pandoc#toc#position='right'` work.

fix(autoload/toc.vim): fix Issue #368

---

ftdetect/pandoc.vim
ftplugin/pandoc.vim

Since
```viml
def LoadFTPlugin()
if exists("b:undo_ftplugin")
legacy exe b:undo_ftplugin
unlet! b:undo_ftplugin b:did_ftplugin
endif
...
enddef
```
unsets b:did_ftplugin, but not b:pandoc_loaded, reloading the filetype will not reaload the ftplugin.
Instead we remove the autocmd's that set the markdown filetype
Closes #237

use standard b:did_ftplugin instead of custom variable b:pandoc_loaded

---

python3/vim_pandoc/helpparser.py

Close Issue #457.
Change from string.replace() to re.sub in get_extensions() to strip leading space and/or + and - from pandoc --list-extensions. Maintain backwards compatibility for versions that include the space character. get_extensions() expected a space at the beginning of each line, which fails because pandoc --list-extensions no longer includes the space.

fix(helpparser): regex parse list-extnsions

---

python3/vim_pandoc/helpparser.py

Problem: Pandoc command fails after users upgrade to Pandoc v3.1.
On newer versions of Pandoc (v3.1.*), no `--trace` option is present from the help menu command line.
This corrects commit 05f110280326e7a389288f1a88f58f1b5901c6fb in a backwards compatible way.
Fixes #450

Fix ValueError from missing --trace option in Pandoc v3.1

---

python3/vim_pandoc/bib/fallback.py

Python versions >= 3.12 throw an error if a string contains an escape sequence that is not known to python.  This can easily be tested with `python3 -c '"\s"'`.
https://docs.python.org/3/whatsnew/changelog.html#python-3-12-0-alpha-2

Use raw python strings for some regexes

---

autoload/pandoc/hypertext.vim

Without the added shellescape some URLs don't open up on Mac, as the shell interprets the content wrongly (especially question marks). Adding the same procedures as for 'unix' corrects the issue.

OpenSystem for Mac should do the same escaping as for unix.
